export { default as Home} from './Home'
export { default as Channel} from './users/Channel'
export { default as Collection} from './users/Collection'
export { default as Subscription} from './Subscription'
export { default as Watch} from './Watch'
export { default as Uploaded} from './Uploaded'
export { default as Search} from './Search'
export { default as Mix} from './users/Mix'
export { default as Liked} from './users/Liked'
export { default as WatchLater} from './users/WatchLater'
export { default as Shorts} from './Shorts'
export { default as Saved} from './users/Saved'
export { default as Studio} from './users/Studio'
export { default as Music} from './Music'
export { default as Histori} from './users/Histori'
export { default as Trends} from './Trends'
export { default as Beranda } from './subChannel/Beranda'
export { default as Video } from './subChannel/Video'
export { default as Release } from './subChannel/Release'
export { default as Playlist } from './subChannel/Playlist'
export { default as Comunity } from './subChannel/Comunity'
export { default as ChannelShorts } from './subChannel/ChannelShorts'
export { default as Stream } from './subChannel/Stream'